# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('loginname', models.CharField(max_length=150)),
                ('truename', models.CharField(max_length=60)),
                ('groupname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'v_userinfo_test',
                'managed': False,
            },
        ),
    ]
