# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posttypes',
            fields=[
                ('id', models.IntegerField(db_column=b'Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'Name', max_length=255)),
            ],
            options={
                'db_table': 'posttypes',
            },
        ),
    ]
