# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_posttypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posttypes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
